### ISSUE TITLE
readyset-server command doesn't have --username flag

### ISSUE THREAD

**Issue by alidevjimmy** [readysettech/docs-deprecated#111]
[readyset-server cli](https://docs.readyset.io/reference/cli/readyset-server) doesn't have --username and --password flags.

**Comment by altmannmarcelo** [comment]
https://docs.readyset.io/reference/cli/readyset-server#start-readyset 

![Screenshot from 2023-12-07 12-29-43](https://github.com/readysettech/docs/assets/2588511/0ec56416-ef8c-47b8-a74e-ba0baffda674)
