### ISSUE TITLE
Feedback for “Supported Queries”

### ISSUE THREAD

**Issue by BenSandeen** [readysettech/docs-deprecated#133]
What does it mean when the docs say it “doesn’t support” queries?  Will it crash if we use those queries?  Or will it just fail to cache stuff and transparently pass the data through?

**Comment by alanarenda** [comment]
The latter– when queries aren't supported, they get proxied through to your primary database.

**Comment by BenSandeen** [comment]
Thanks for clarifying!  It might be helpful if the docs were updated to explain that
